// plugin.cpp : Defines the entry point for the DLL application.
//

#include "stdafx.h"
#include "IPlugin.h"

#include <math.h>
#include <cmath>
#include <stdio.h>
#include <stdlib.h>
#include <iostream>//to use cout


using namespace std;


////////////////////////////////////////////////////////////////////////
// A concrete plugin implementation
////////////////////////////////////////////////////////////////////////

// Photo-Reactor Plugin class

//****************************************************************************
//This code has been generated by the Mediachance photo reactor Code generator.


#define AddParameter(N,S,V,M1,M2,T,D) {strcpy (pParameters[N].m_sLabel,S);pParameters[N].m_dValue = V;pParameters[N].m_dMin = M1;pParameters[N].m_dMax = M2;pParameters[N].m_nType = T;pParameters[N].m_dSpecialValue = D;}

#define GetValue(N) (pParameters[N].m_dValue)
#define GetValueY(N) (pParameters[N].m_dSpecialValue)

#define SetValue(N,V) {pParameters[N].m_dValue = V;}

#define GetBOOLValue(N) ((BOOL)(pParameters[N].m_dValue==pParameters[N].m_dMax))

// if it is not defined, then here it is
//#define RGB(r,g,b) ((COLORREF)(((BYTE)(r)|((WORD)((BYTE)(g))<<8))|(((DWORD)(BYTE)(b))<<16)))

#define PARAM_BLENDTYPE	0
#define PARAM_ITERATIONS	1

#define NUMBER_OF_USER_PARAMS 2

#define MIN(a,b) (((a)<(b))?(a):(b))
#define MAX(a,b) (((a)>(b))?(a):(b))


class Plugin1 : public IPlugin	
{
public:

		//Plugin Icon:
	//you can add your own icon by creating 160x100 png file, naming it the same as plugin dll and then placing it in the plugins folder
	//otherwise a generic icon will be use


	//this is the title of the box in workspace. it should be short
	const char* GetTitle () const
	{
		return "Andy's Stylized";
	}
	
	// this will appear in the help pane, you can put your credits and short info
	const char* GetDescription () const
	{
		return "Stylized is a non photo realistic image processing recipe.  It takes your image runs through a sobel filter to produce edge detecting black lines and blends those lines on top of the original image.  Increase the iterations to make the edge detecting lines thicker.  Place an edge preserving smooth on the image prior to this filter to produce a cartoon like image.";
	}

	// BASIC PARAMETERS
	// number of inputs 0,1 or 2
	int GetInputNumber ()
	{
		return 1;
	}

	// number of outputs 0 or 1
	int GetOutputNumber ()
	{
		return 1;
	}

	int GetBoxColor ()
	{
		return RGB(44,78,119);
	}

	int GetTextColor ()
	{
		return RGB(165,236,255);
	}

	// width of the box in the workspace
	// valid are between 50 and 100
	int GetBoxWidth ()
	{
		return 80;
	}

	// set the flags
	// see the interface builder
	// ex: nFlag = FLAG_FAST_PROCESS | FLAG_HELPER;

	//FLAG_NONE same as zero	Default, no other flags set
	//FLAG_UPDATE_IMMEDIATELY	It is very fast process that can update immediately. When user turns the sliders on UI the left display will update
	//							Use Update Immediately only for fast and single loop processes, for example Desaturate, Levels.
	//FLAG_HELPER				It is an helper object. Helper objects will remain visible in Devices and they can react to mouse messages. Example: Knob, Monitor, Bridge Pin
	//FLAG_BINDING				Binding object, attach to other objects and can change its binding value. It never goes to Process_Data functions.  Example: Knob, Switch, Slider
	//FLAG_DUMMY				It is only for interface but never process any data. Never goes to Process_Data functions. Example: Text note
	//FLAG_SKIPFINAL			Process data only during designing, doesn't process during final export. Example: Monitor, Vectorscope 
	//FLAG_LONGPROCESS			Process that takes > 1s to finish. Long Process will display the Progress dialog and will prevent user from changing values during the process.
	//FLAG_NEEDSIZEDATA		    Process need to know size of original image, the zoom and what part of image is visible in the preview. When set the plugin will receive SetSizeData
	//FLAG_NEEDMOUSE			Process will receive Mouse respond data from the workplace. This is only if your object is interactive, for example Knob, Slider

	int GetFlags ()
	{
		// it is fast process
		int nFlag = FLAG_UPDATE_IMMEDIATELY;
		
		return nFlag;
	}


	// User Interface Build
	// there is maximum 29 Parameters

	int GetUIParameters (UIParameters* pParameters)
	{

		// label, value, min, max, type_of_control, special_value
		// use the UI builder in the software to generate this

		AddParameter( PARAM_BLENDTYPE ,"Multiply|Linear Burn", 0, 0, 1, TYPE_ONEOFMANY, 0);
		AddParameter( PARAM_ITERATIONS ,"Iterations", 1.0, 1.0, 10.0, TYPE_SLIDER, 0.0);

		return NUMBER_OF_USER_PARAMS;
	}
	


	// Actual processing function for 1 input
	//***************************************************************************************************
	// Both buffers are the same size
	// don't change the IN buffer or things will go bad for other objects in random fashion
	// the pBGRA_out comes already with pre-copied data from pBGRA_in
	// Note: Don't assume the nWidth and nHeight will be every run the same or that it contains the whole image!!!! 
	// This function receives buffer of the actual preview (it can be just a crop of image when zoomed in) and during the final calculation of the full buffer
	// this is where the image processing happens
	virtual void Process_Data (BYTE* pBGRA_out,BYTE* pBGRA_in, int nWidth, int nHeight, UIParameters* pParameters)
	{
		//List of Parameters

		//BYTE type = (int)GetValue(PARAM_TYPE);
		BYTE blend = (int)GetValue(PARAM_BLENDTYPE);
		int iterations = (int)GetValue(PARAM_ITERATIONS);

		int imagesize = nWidth * nHeight * 4;

		float* temp = new float[nWidth * nHeight * 4];
		memset( temp, 0.0, sizeof(imagesize) );

		float* output = new float[nWidth * nHeight * 4];
		memset( output, 0.0, sizeof(imagesize) );

		int widthminus = nWidth - 1;
		int heightminus = nHeight - 1;

		float colorDepth = 255.0;

		//place our image in a seperate array in the 0-1 range, where 0 is darkest and 1 is lightest
		for (int x = 0; x < nWidth; x++)
		{
			for (int y = 0; y < nHeight; y++)
			{
				int nIdx = x * 4 + y * 4 * nWidth;

				float red = pBGRA_in[nIdx + CHANNEL_R];
				float green = pBGRA_in[nIdx + CHANNEL_G];
				float blue = pBGRA_in[nIdx + CHANNEL_B];

				temp[nIdx + CHANNEL_R] = red / colorDepth;
				temp[nIdx + CHANNEL_G] = green / colorDepth;
				temp[nIdx + CHANNEL_B] = blue / colorDepth;

				//output
				output[nIdx + CHANNEL_R] = red / colorDepth;
				output[nIdx + CHANNEL_G] = green / colorDepth;
				output[nIdx + CHANNEL_B] = blue / colorDepth;
			}//end x
		}//end y


		//convert output to monochrome and invert
		for (int x = 0; x < nWidth; x++)
		{
			for (int y = 0; y < nHeight; y++)
			{
				int nIdx = x * 4 + y * 4 * nWidth;

				float wR = 0.299;
				float wG = 0.578;
				float wB = 0.114;
				// [0.212656, 0.715158, 0.072186]

				float muRed1 = temp[nIdx + CHANNEL_R];
				float muGreen1 = temp[nIdx + CHANNEL_G];
				float muBlue1 = temp[nIdx + CHANNEL_B];

				float luma = (wR * muRed1) + (wG * muGreen1) + (wB * muBlue1);

				temp[nIdx + CHANNEL_R] = luma;
				temp[nIdx + CHANNEL_G] = luma;
				temp[nIdx + CHANNEL_B] = luma;
			}
		}

		//sobel effect
		{
			//char sBuffer1[400];

			float* dxdy=new float[nWidth * nHeight * 4]; //where sobel will be placed
			memset( dxdy, 0.0, sizeof(imagesize) );

			float* dx=new float[nWidth * nHeight * 4]; //where sobel will be placed
			memset( dx, 0.0, sizeof(imagesize) );

			float* dy=new float[nWidth * nHeight * 4]; //where sobel will be placed
			memset( dy, 0.0, sizeof(imagesize) );




			float sobel[3][3] = 
			{ 
				{1.0, 2.0, 1.0},
				{0.0, 0.0, 0.0},
				{-1.0, -2.0, -1.0}
			};

			for (int iter = 0; iter < iterations; iter++)//iterations
			{

				//dx formula
				for(int x = 1; x < widthminus; x++)
				{					
					for(int y = 1; y < heightminus; y++)
					{
						int nIdx1 = x * 4 + y * 4 * nWidth;

						int sx = 0;
						int sy = 0;

						//This is our Kernel
						for(int j = -1; j < 2; j++)
						{					
							for(int i = -1; i < 2; i++)
							{
								int nIdx2 = (i + x) * 4 + (j + y) * 4 * nWidth;

								//this slides / moves along the kernel to collect the neighboring pixels
								float redKernelSlider = temp[nIdx2 + CHANNEL_R];
								float greenKernelSlider = temp[nIdx2 + CHANNEL_G];
								float blueKernelSlider = temp[nIdx2 + CHANNEL_B];
								//this slides / moves along the kernel to collect the neighboring pixels

								dx[nIdx1 + CHANNEL_R] += sobel[sy][sx] * redKernelSlider;
								dx[nIdx1 + CHANNEL_G] += sobel[sy][sx] * greenKernelSlider;
								dx[nIdx1 + CHANNEL_B] += sobel[sy][sx] * blueKernelSlider;

								sx++;
							}//end i
							sy++;
						}//end j
					}//end y
				}//end x


				//dy formula
				for(int y = 1; y < heightminus; y++)
				{
					for(int x = 1; x < widthminus; x++)
					{
						int nIdx1 = x * 4 + y * 4 * nWidth;

						int sx = 0;
						int sy = 0;

						//This is our Kernel
						for(int i = -1; i < 2; i++)
						{					
							for(int j = -1; j < 2; j++)
							{
								int nIdx2 = (i + x) * 4 + (j + y) * 4 * nWidth;

								//this slides / moves along the kernel to collect the neighboring pixels
								float redKernelSlider = temp[nIdx2 + CHANNEL_R];
								float greenKernelSlider = temp[nIdx2 + CHANNEL_G];
								float blueKernelSlider = temp[nIdx2 + CHANNEL_B];
								//this slides / moves along the kernel to collect the neighboring pixels

								dy[nIdx1 + CHANNEL_R] += sobel[sx][sy] * redKernelSlider;
								dy[nIdx1 + CHANNEL_G] += sobel[sx][sy] * greenKernelSlider;
								dy[nIdx1 + CHANNEL_B] += sobel[sx][sy] * blueKernelSlider;

								sy++;
							}//end i
							sx++;
						}//end j
					}//end y
				}//end x
							
				//combine to create gradient magnitude
				for (int x = 0; x < nWidth; x++)
				{
					for (int y = 0; y < nHeight; y++)
					{
						int nIdx1 = x * 4 + y * 4 * nWidth;

						float dxRweight = dx[nIdx1 + CHANNEL_R];
						float dxGweight = dx[nIdx1 + CHANNEL_G];
						float dxBweight = dx[nIdx1 + CHANNEL_B];

						float dyRweight = dy[nIdx1 + CHANNEL_R];
						float dyGweight = dy[nIdx1 + CHANNEL_G];
						float dyBweight = dy[nIdx1 + CHANNEL_B];

						dxdy[nIdx1 + CHANNEL_R] =  sqrt(dxRweight * dxRweight) + (dyRweight * dyRweight);
						dxdy[nIdx1 + CHANNEL_G] =  sqrt(dxGweight * dxGweight) + (dyGweight * dyGweight);
						dxdy[nIdx1 + CHANNEL_B] =  sqrt(dxBweight * dxBweight) + (dyBweight * dyBweight);
					}
				}

			}//end iterations



			//test point
			for (int x = 0; x < nWidth; x++)
			{
				for (int y = 0; y < nHeight; y++)
				{
					int nIdx = x * 4 + y * 4 * nWidth;

					float nR = dxdy [nIdx + CHANNEL_R];
					float nG = dxdy [nIdx + CHANNEL_G];
					float nB = dxdy [nIdx + CHANNEL_B];

					//float nR = dy [nIdx + CHANNEL_R];
					//float nG = dy [nIdx + CHANNEL_G];
					//float nB = dy [nIdx + CHANNEL_B];

				//	pBGRA_out[nIdx + CHANNEL_R] = CLAMP255(nR * colorDepth);
				//	pBGRA_out[nIdx + CHANNEL_G] = CLAMP255(nG * colorDepth);
				//	pBGRA_out[nIdx + CHANNEL_B] = CLAMP255(nB * colorDepth);
				}
			}

			//copy to temp
			for (int x = 0; x < nWidth; x++)
			{
				for (int y = 0; y < nHeight; y++)
				{
					int nIdx = x * 4 + y * 4 * nWidth;

					float nR = dxdy [nIdx + CHANNEL_R];
					float nG = dxdy [nIdx + CHANNEL_G];
					float nB = dxdy [nIdx + CHANNEL_B];
					
					temp[nIdx + CHANNEL_R] = nR;
					temp[nIdx + CHANNEL_G] = nG;
					temp[nIdx + CHANNEL_B] = nB;
				}
			}

			delete [] dx;
			delete [] dy;
			delete [] dxdy;

			//The basic algorithm to get magnitude and orientation of the gradient is as follows:
			//Compute Sobel in the X direction (Sx).
			//Compute Sobel in the Y direction (Sy).
			//Compute the gradient magnitude sqrt(Sx*Sx + Sy*Sy).

		}//end sobel




		//invert
		for (int x = 0; x < nWidth; x++)
		{
			for (int y = 0; y < nHeight; y++)
			{
				int nIdx = x * 4 + y * 4 * nWidth;

				float nR = temp [nIdx + CHANNEL_R];
				float nG = temp [nIdx + CHANNEL_G];
				float nB = temp [nIdx + CHANNEL_B];

				temp[nIdx + CHANNEL_R] = 1.0 - nR;
				temp[nIdx + CHANNEL_G] = 1.0 - nG;
				temp[nIdx + CHANNEL_B] = 1.0 - nB;
			}
		}





		//blend
		{
			float nR = 0.0;
			float nG = 0.0;
			float nB = 0.0;

			for (int x = 0; x < nWidth; x++)
			{
				for (int y = 0; y < nHeight; y++)
				{
					int nIdx = x * 4 + y * 4 * nWidth;

					float nR1 = temp[nIdx + CHANNEL_R];
					float nG1 = temp[nIdx + CHANNEL_G];
					float nB1 = temp[nIdx + CHANNEL_B];

					float nR2 = output[nIdx + CHANNEL_R];
					float nG2 = output[nIdx + CHANNEL_G];
					float nB2 = output[nIdx + CHANNEL_B];

					//((uint8)((A * B) / 255))
					//multiply
					if (blend == 0)
					{
						nR = ((nR1 * nR2) / 1.0);
						nG = ((nG1 * nG2) / 1.0);
						nB = ((nB1 * nB2) / 1.0);
					}

					//try linear burn with layers reversed
					//(ChannelBlend_Subtract(A,B))
					if (blend == 1)
					{
						// Math: A+B−1
						nR = (nR2 + nR1 - 1.0);
						nG = (nG2 + nG1 - 1.0);
						nB = (nB2 + nB1 - 1.0);
					}

					output[nIdx + CHANNEL_R] = nR;
					output[nIdx + CHANNEL_G] = nG;
					output[nIdx + CHANNEL_B] = nB;
				}
			}
		}



		//output
		for (int x = 0; x < nWidth; x++)
		{
			for (int y = 0; y < nHeight; y++)
			{
				int nIdx = x * 4 + y * 4 * nWidth;

				float nR = output [nIdx + CHANNEL_R];
				float nG = output [nIdx + CHANNEL_G];
				float nB = output [nIdx + CHANNEL_B];

				pBGRA_out[nIdx + CHANNEL_R] = CLAMP255(nR * colorDepth);
				pBGRA_out[nIdx + CHANNEL_G] = CLAMP255(nG * colorDepth);
				pBGRA_out[nIdx + CHANNEL_B] = CLAMP255(nB * colorDepth);
			}
		}


#pragma endregion

		delete[] temp;
		delete[] output;

	}//end routine



						


	// actual processing function for 2 inputs
	//********************************************************************************
	// all buffers are the same size
	// don't change the IN buffers or things will go bad
	// the pBGRA_out comes already with copied data from pBGRA_in1
	virtual void Process_Data2 (BYTE* pBGRA_out, BYTE* pBGRA_in1, BYTE* pBGRA_in2, int nWidth, int nHeight, UIParameters* pParameters)
	{

	}


	//*****************Drawing functions for the BOX *********************************
	//how is the drawing handled
	//DRAW_AUTOMATICALLY	the main program will fully take care of this and draw a box, title, socket and thumbnail
	//DRAW_SIMPLE_A			will draw a box, title and sockets and call CustomDraw
	//DRAW_SIMPLE_B			will draw a box and sockets and call CustomDraw
	//DRAW_SOCKETSONLY      will call CustomDraw and then draw sockets on top of it
	
	// highlighting rectangle around is always drawn except for DRAW_SOCKETSONLY

	virtual int GetDrawingType ()
	{

		int nType = DRAW_AUTOMATICALLY;

		return nType;

	}


	// Custom Drawing
	// custom drawing function called when drawing type is different than DRAW_AUTOMATICALLY
	// it is not always in real pixels but scaled depending on where it is drawn
	// the scale could be from 1.0 to > 1.0
	// so you always multiply the position, sizes, font size, line width with the scale
	
	virtual void CustomDraw (HDC hDC, int nX,int nY, int nWidth, int nHeight, float scale, BOOL bIsHighlighted, UIParameters* pParameters)
	{
	}


	//************ Optional Functions *****************************************************************************************
	// those functions are not necessary for normal effect, they are mostly for special effects and objects


	// Called when FLAG_HELPER set. 
	// When UI data changed (user turned knob) this function will be called as soon as user finish channging the data
	// You will get the latest parameters and also which parameter changed
	// Normally for effects you don't have to do anything here because you will get the same parameters in the process function
	// It is only for helper objects that may not go to Process Data 
	BOOL UIParametersChanged (UIParameters* pParameters, int nParameter)
	{
		
		return FALSE;
	}

	// when button is pressed on UI, this function will be called with the parameter and sub button (for multi button line)
	BOOL UIButtonPushed (int nParam, int nSubButton, UIParameters* pParameters)
	{

		return TRUE;
	}


	// Called when FLAG_NEEDSIZEDATA set
	// Called before each calculation (Process_Data)
	// If your process depends on a position on a frame you may need the data to correctly display it because Process_Data receives only a preview crop
	// Most normal effects don't depend on the position in frame so you don't need the data
	// Example: drawing a circle at a certain position requires to know what is displayed in preview or the circle will be at the same size and position regardless of zoom
	
	// Note: Even if you need position but you don't want to mess with the crop data, just ignore it and pretend the Process_Data are always of full image (they are not). 
	// In worst case this affects only preview when using zoom. The full process image always sends the whole data

	// nOriginalW, nOriginalH - the size of the original - full image. If user sets Resize on input - this will be the resized image
	// nPreviewW, nPreviewH   - this is the currently processed preview width/height - it is the same that Process_Data will receive
	//                        - in full process the nPreviewW, nPreviewH is equal nOriginalW, nOriginalH
	// Crop X1,Y1,X2,Y2       - relative coordinates of preview crop rectangle in <0...1>, for full process they are 0,0,1,1 (full rectangle)	
	// dZoom                  - Zoom of the Preview, for full process the dZoom = 1.0
	void SetSizeData(int nOriginalW, int nOriginalH, int nPreviewW, int nPreviewH, double dCropX1, double dCropY1, double dCropX2, double dCropY2, double dZoom)
	{

		// so if you need the position and zoom, this is the place to get it.
		// Note: because of IBM wisdom the internal bitmaps are on PC always upside down, but the coordinates are not


	}


	// ***** Mouse handling on workplace *************************** 
	// only if FLAG_NEEDMOUSE is set
	//****************************************************************
	//this is for special objects that need to receive mouse, like a knob or slider on workplace
	// normally you use this for FLAG_BINDING objects

	// in coordinates relative to top, left corner of the object (0,0)
	virtual BOOL MouseButtonDown (int nX, int nY, int nWidth, int nHeight, UIParameters* pParameters)
	{
		
		// return FALSE if not handled
		// return TRUE if handled
		return FALSE;
	}

	// in coordinates relative to top, left corner of the object (0,0)
	virtual BOOL MouseMove (int nX, int nY, int nWidth, int nHeight, UIParameters* pParameters)
	{
	

		return FALSE;
	}
	
	// in coordinates relative to top, left corner of the object (0,0)
	virtual BOOL MouseButtonUp (int nX, int nY, int nWidth, int nHeight, UIParameters* pParameters)
	{
		
		// Note: if we changed data and need to recalculate the flow we need to return TRUE

		// return FALSE if not handled
		// return TRUE if handled
		
		return TRUE;
	}


};

extern "C"
{
	// Plugin factory function
	__declspec(dllexport) IPlugin* Create_Plugin ()
	{
		//allocate a new object and return it
		return new Plugin1 ();
	}
	
	// Plugin cleanup function
	__declspec(dllexport) void Release_Plugin (IPlugin* p_plugin)
	{
		//we allocated in the factory with new, delete the passed object
		delete p_plugin;
	}
	
}


// this is the name that will appear in the object library
extern "C" __declspec(dllexport) char* GetPluginName()
{
	return "Andy's Stylized";	
}


// This MUST be unique string for each plugin so we can save the data

extern "C" __declspec(dllexport) char* GetPluginID()
{
	
	
	return "com.lumafilters.Stylized";
	
}


// category of plugin, for now the EFFECT go to top library box, everything else goes to the middle library box
extern "C" __declspec(dllexport) int GetCategory()
{
		
	return CATEGORY_EFFECT;
	
}

